#!/bin/zsh
##? autoload-dir - autoload all function files in specified directory.

defun autoload-dir() {
    [[ -d "$1" ]] || return 1

    emulate -L zsh;
    setopt localoptions extendedglob globdots globstarshort nullglob rcquotes \
	   nolocalloops

    # set in paths
    fpath=( ${1:q} ${1:q}/**/*(/FN) $fpath)

    # define functions autoloaded
    {
	local -a _paths=( ${1:q} ${1:q}/**/*(.N) ) &&
	    _paths=( ${_paths[@]:a} )
	for _name in ${_paths[@]:t}; do
	    autoload-ignore ||
		autoload -Uz ${_name}
	done
    }
}

autoload-dir ${@}
