#!/bin/zsh
##? autoload-dir - autoload all function files in specified directory.

[[ -d "$1" ]] || return 1
fpath=("$1" $fpath)
local fn;
for fn in "$1"/*(.N); do
    case ${fn:t} in
	'_'*) continue;;
	*'~') continue;;
	'#'*) continue;;
    esac
    autoload -Uz${ZDOTDEBUG:+t} $fn
done
