#!/bin/zsh
##? conf.d - Use a Fish-like conf.d directory for sourcing configs.

#function zsh_confd {
  local zfile
  for zfile in $ZDOTDIR/conf.d/*.zsh(N); do
    [[ $zfile:t != '~'* ]] || continue
    . $zfile
  done
#}
