#!/bin/zsh
# trace shell execution and redirect output to dedicated files in /tmp

setopt local_options
setopt extended_glob warn_create_global typeset_silent \
       no_short_loops rc_quotes no_auto_pushd numeric_glob_sort \
       multios

set -x

whence plugin-load &&
  plugin-load xdg

typeset -Ag ztrace

local cmd=${1-status}
local name=${2:-zsh}
local sockfile=${XDG_RUNTIME_DIR}/ztrace.sock

name=${name:t:r}

local -a stack &&
  [[ -n "${ztrace[stack]}" ]] &&
  stack=( ${(@qs:X:)ztrace[stack]} )

case $cmd in
  up)
    stack+=( "$name" )
    ztrace[stack]=${(qj:X:)stack}
    (( ${#stack} == 1 )) &&
      exec 3>&2 2>(logger -s -t "${name}") &&
      setopt xtrace source_trace
    ;;
  down)
    shift -p stack &&
      stack=( $stack ) # remove last empty elements
    ztrace[stack]=${(qj:X:)stack}
    (( ${#stack} > 0  )) &&
      return
    setopt noxtrace nosource_trace &&
      exec 2>&2 3>&- &&
    ;;
  status)
    [[ ${#stack} -gt 0 ]]
    ;;
esac

set +x
